# Generated by Django 6.0 on 2025-12-13 10:06

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_author_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(default=news.models.default_published_date),
        ),
    ]
