# Generated by Django 6.0 on 2025-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the podcast episode', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the podcast episode')),
                ('host', models.CharField(help_text='Host or presenter of the podcast', max_length=200)),
                ('guest', models.CharField(blank=True, help_text='Guest speaker(s) if any', max_length=200)),
                ('youtube_url', models.URLField(help_text='URL to the YouTube video')),
                ('thumbnail', models.URLField(blank=True, help_text='YouTube thumbnail URL', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('published_date', models.DateTimeField(help_text='Date when the podcast was published')),
                ('episode_number', models.IntegerField(blank=True, help_text='Episode number if applicable', null=True)),
                ('category', models.CharField(blank=True, help_text='Category or topic of the podcast', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags', max_length=500)),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('likes', models.IntegerField(default=0, help_text='Number of likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
