# Generated by Django 6.0 on 2025-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='views',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the podcast', null=True, upload_to='podcasts/'),
        ),
    ]
