# Generated by Django 6.0 on 2025-12-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('bill_type', models.CharField(choices=[('government', 'Government'), ('private_member', 'Private Member')], max_length=50)),
                ('year_introduced', models.DateField()),
                ('mover', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(help_text='Committee assigned to', max_length=200)),
                ('status', models.CharField(choices=[('1st_reading', '1st Reading'), ('2nd_reading', '2nd Reading'), ('3rd_reading', '3rd Reading'), ('passed', 'Passed by Parliament'), ('assented', 'Assented to by the President')], default='1st_reading', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('1st_reading', '1st Reading'), ('2nd_reading', '2nd Reading'), ('3rd_reading', '3rd Reading')], max_length=50)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='bill_documents/')),
                ('committee_report', models.FileField(blank=True, null=True, upload_to='committee_reports/')),
                ('analysis', models.FileField(blank=True, null=True, upload_to='bill_analysis/')),
                ('mp_photo', models.ImageField(blank=True, null=True, upload_to='mp_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='trackers.bill')),
            ],
            options={
                'verbose_name': 'Bill Reading',
                'verbose_name_plural': 'Bill Readings',
                'ordering': ['date'],
                'unique_together': {('bill', 'stage')},
            },
        ),
    ]
