# Generated by Django 6.0 on 2025-12-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_update_party_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of the data', unique=True)),
                ('national_debt', models.DecimalField(decimal_places=2, help_text='National debt in millions UGX', max_digits=20)),
                ('gdp', models.DecimalField(decimal_places=2, help_text='GDP in millions UGX', max_digits=20)),
                ('interest', models.DecimalField(decimal_places=2, default=0, help_text='Interest payments in millions UGX', max_digits=20)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0, help_text='Total government expenditure in millions UGX', max_digits=20)),
                ('debt_per_citizen', models.DecimalField(decimal_places=2, default=0, help_text='Debt per citizen in UGX', max_digits=15)),
                ('gdp_per_capita', models.DecimalField(decimal_places=2, default=0, help_text='GDP per capita in UGX', max_digits=15)),
                ('per_capita_income', models.DecimalField(decimal_places=2, default=0, help_text='Per capita income in UGX', max_digits=15)),
                ('population', models.BigIntegerField(blank=True, help_text='Population for the year', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Debt Data',
                'verbose_name_plural': 'Debt Data',
                'ordering': ['year'],
            },
        ),
    ]
