# Generated by Django 6.0 on 2025-12-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0004_debtdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('energy', 'Energy'), ('transport', 'Transport'), ('health', 'Health'), ('education', 'Education'), ('agriculture', 'Agriculture'), ('water', 'Water and Sanitation'), ('ict', 'ICT'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], max_length=50)),
                ('label', models.CharField(help_text='Project name or description', max_length=500)),
                ('approved_amount', models.DecimalField(decimal_places=2, help_text='Approved loan amount', max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('UGX', 'Uganda Shilling')], default='USD', max_length=3)),
                ('source', models.CharField(choices=[('world_bank', 'World Bank'), ('imf', 'International Monetary Fund'), ('adb', 'African Development Bank'), ('china', 'China'), ('eu', 'European Union'), ('bilateral', 'Bilateral Agreement'), ('other', 'Other')], help_text='Loan source/creditor', max_length=50)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-approval_date', '-created_at'],
            },
        ),
    ]
