# Generated by Django 6.0 on 2025-12-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hansard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hansard name', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hansard',
                'ordering': ['-created_at'],
            },
        ),
    ]
