# Generated by Django 6.0 on 2025-12-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0006_hansard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Budget document name', max_length=200)),
                ('financial_year', models.CharField(help_text='Financial year (e.g., 2024/2025)', max_length=20)),
                ('file', models.FileField(help_text='Budget PDF document', upload_to='budgets/')),
                ('budget_total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget amount in UGX', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-financial_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Paper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hansard',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Hansard', 'verbose_name_plural': 'Hansards'},
        ),
    ]
