# Generated by Django 6.0 on 2026-01-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0010_remove_bill_comments_remove_bill_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hansard',
            name='date_received',
            field=models.DateField(blank=True, help_text='Date the Hansard was received', null=True),
        ),
        migrations.AddField(
            model_name='orderpaper',
            name='date_received',
            field=models.DateField(blank=True, help_text='Date the order paper was received', null=True),
        ),
        migrations.AlterField(
            model_name='hansard',
            name='date',
            field=models.DateField(blank=True, help_text='Date of the Hansard session', null=True),
        ),
    ]
