# Generated by Django 6.0 on 2025-12-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_donationsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsubmission',
            name='country',
            field=models.CharField(default='Uganda', max_length=100),
        ),
    ]
