# Generated by Django 6.0 on 2026-01-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_explainers_name_alter_partnerpublication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpublication',
            name='date_received',
            field=models.DateField(blank=True, help_text='Date the publication was received', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='date_received',
            field=models.DateField(blank=True, help_text='Date the report was received', null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='date_received',
            field=models.DateField(blank=True, help_text='Date the statement was received', null=True),
        ),
    ]
